force-app/main/default/objects/Evony_GeneralSpecialtySkills__c/fields/General__c.field-meta.xml
<CustomField>
    <fullName>General__c</fullName>
    <label>General</label>
    <referenceTo>Evony_General__c</referenceTo>
    <relationshipLabel>General Specialty Skills</relationshipLabel>
    <relationshipName>GeneralSpecialtySkills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Evony_GeneralSpecialtySkills__c/fields/SpecialtySkill__c.field-meta.xml
<CustomField>
    <fullName>SpecialtySkill__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Specialty Skill</label>
    <referenceTo>Evony_SpecialtySkill__c</referenceTo>
    <relationshipLabel>General Specialty Skills</relationshipLabel>
    <relationshipName>GeneralSpecialtySkills</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evony_SpecialtySkill__c/Evony_SpecialtySkill__c.object-meta.xml
<CustomObject>
    <label>Specialty Skill</label>
    <nameField>
        <label>SpecialiSkill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialty Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General__c/General__c.object-meta.xml
<CustomObject>
    <label>General</label>
    <nameField>
        <label>General Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Evony_GeneralSpecialtySkillSelector.cls
public class Evony_GeneralSpecialtySkillSelector extends Selector {

    private static final Evony_GeneralSpecialtySkillSelector selector = new Evony_GeneralSpecialtySkillSelector();
    
    public Evony_GeneralSpecialtySkillSelector() {
        super('Evony_GeneralSpecialtySkills__c');
    }

    @AuraEnabled(cacheable = true)
    public static List<Evony_GeneralSpecialtySkills__c> getAllGeneralSpecialtySkillByGeneralsId(List<String> generalsId) {
        Evony_SpecialtySkillSelector specialtySkillSelector = new Evony_SpecialtySkillSelector();

        System.debug('generalsId = ' + generalsId);

        // Create string to use to get all fields from Evony_SpecialtySkill__c
        String specialtySkillReference = 'SpecialtySkill__r.';
        Set<String> specialtySkillFieldsFormatted = new Set<String>();
        Set<String> specialtySkillFields = specialtySkillSelector.getFieldNameList();
        specialtySkillFields.removeAll(ObjectCommonFields.getAllFieldsExcept(ObjectCommonFields.ID));

        for(String specialtySkillField : specialtySkillFields) {
            specialtySkillFieldsFormatted.add(specialtySkillReference + specialtySkillField);
        }

        // Configure Fields and Where Clause
        selector.fieldNameList.addAll(specialtySkillFieldsFormatted);
        selector.whereClause = 'General__c IN :generalsId';

        return Database.query(selector.createQuery());
    }
}